### ISSUE TITLE
Apparent discrepancies between net income and EMTR chart

### ISSUE THREAD

**Issue by MaxGhenis** [Treasury-Analytics-and-Insights/IncomeExplorer#7]
The below pair of charts shows up with default inputs and 2023 policy parameters. At two points they seem to misalign:
* At ~1 hour, the EMTR chart spikes but the net income chart doesn't fall (maybe this is a resolution thing)
* At 20 hours, the net income chart jumps up, but there's no corresponding EMTR dip
![image](https://github.com/Treasury-Analytics-and-Insights/IncomeExplorer/assets/6076111/875bf917-374f-4802-b949-c814892a6a39)

**Comment by MeghanStephensNZ** [comment]
I had a look and this is a bug in the code that choses between either Working for Families and core benefits - the rest of the emtr profile is correct, its just at the change point. Will fix.

**Comment by MeghanStephensNZ** [comment]
Fixed
