### ISSUE TITLE
Increase default hourly wage to >= minimum wage

### ISSUE THREAD

**Issue by MaxGhenis** [Treasury-Analytics-and-Insights/IncomeExplorer#8]
The current default wage is $20, which is less than the minimum wage of $22.70

https://github.com/Treasury-Analytics-and-Insights/IncomeExplorer/blob/a0c18a77ec27383c5210cfe7f09a1ac1a553aee3/ui.R#L35-L40

**Comment by YvonneWanggg** [comment]
Will update this
